### ISSUE TITLE
All "Narrow the Scope" entries coming back as "Not Valid

### ISSUE THREAD

**Issue by 65pony** [newrelic/nr1-metrics-aggregator#36]
[NOTE]: # ( All "Narrow the Scope" entries coming back as "Not Valid )

## Description
When trying to Narrow down the scope to reduce cardinality all entries are coming back as "Not Valid". I tried both "basic" and advanced NRQL with the same result.

## Steps to Reproduce

Using Transaction eventtype. To limit scope I used where request.uri like abc. I also used various attributes, operators and values. All come back as "Not Valid"

**Comment by jake-codes** [comment]
Closing this for now. Re-open if you're able to describe this further.
