### ISSUE TITLE
[3rd Party Apps] Not able to see any E2M rules

### ISSUE THREAD

**Issue by danielgblanco** [newrelic/nr1-metrics-aggregator#50]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

We have a bunch of E2M rules created via Terraform and these are currently not displaying in the app. I've checked and all parent and child accounts have permissions and are on the `STABLE` channel.

## Steps to Reproduce

1. Create E2M rule in Terraform
2. Open Metric Aggregator

## Expected Behaviour

Being able to see rules

## Relevant Logs / Console output

![image](https://user-images.githubusercontent.com/4158734/148057589-3c3a75fd-cf7b-4a3f-87bd-e5c3de9158ba.png)

The console (Chrome tools) output contains messages for all rules like the one below:

```
could not parse metric name from rule nrql FROM PageViewTiming SELECT distribution(firstInputDelay) AS rum_fid_distribution FACET myCustomField1, myCustomField2, myCustomField3
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by jpvajda** [comment]
I'm looking into this problem to better understand what may be occurring with this application.

**Comment by jpvajda** [comment]
@jake-codes may have some insights into this issue. 👋

**Comment by jpvajda** [comment]
PR to update in the catalog https://github.com/newrelic/nr1-catalog/pull/425

**Comment by jpvajda** [comment]
the US environment is updated via the catalog manager and I've requested to the platform team to update staging and EU in slack.

**Comment by jake-codes** [comment]
@danielgblanco A fix has been released for this. You should now see the rules in your account.

**Comment by danielgblanco** [comment]
I can see them, that's awesome :) thanks!
