### ISSUE TITLE
Metric Aggregator bug with sticky selector

### ISSUE THREAD

**Issue by jenerallyErrorFree** [newrelic/nr1-metrics-aggregator#63]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
if i create a metric of type distribution, i need to click the distribution query function of course. If i then go to create another distribution metric, the distribution button remains checked but if i continue it creates a summary metric instead. To create a distribution metric i need to uncheck distribution and recheck it.

## Steps to Reproduce
Failure case:
Go to metric aggregator and create a rule based on a metric
Choose Distribution query function
Create rule
Notice that it creates a distribution metric
Click create rule again
Notice that distribution is selected automatically
Click create rule
Notice that the rule made is a summary rule
Success case: Same as above, except instead of leaving distribution selected click to summary first then  back to distribution. Notice that the rule made is a distribution rule

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour
Expect that the distribution selection is cleared when creating a rule. 
I'd also be fine with it creating a distribution metric if that's what is selected. ultimately either case is fine, it resets or it creates the thing it shows as being selected. as long as whatever is created is what is shown

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
New Relic One UI, Metric Aggregator App
[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by jake-codes** [comment]
Thanks for pointing this out. This last push should have fixed this.
